version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build
  unit-test:
    executor:
      name: android/android
    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew testDebug
      - run:
          name: Save test results
          command: ./gradlew testDebug
          when: always
      - store_test_results:
          path: ~/test-results

  android-test:
    executor:
      name: android/android
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
      - run:
          name: Run UI Test
          command: ./gradlew connectedDebugAndroidTest
          when: always
      - store_test_results:
          path: ~/test-results

  debug-build:
    executor:
      name: android/android
    steps:
      - checkout
      - run:
          name: Assemble debug build
          command: ./gradlew assembleDebug
          when: always
      - store_artifacts:
          path: app/build/outputs/apk/debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test
      - android-test
      - debug-build
